### PR TITLE
Move images and downloads directories to root

### LINKED ISSUE #81: Consider moving all images to top-level folder outside of _static
Due to [weird quirks with the way Sphinx generates thumbnails for videos, animations, etc](https://stackoverflow.com/a/16202726), any image link targets are copied into the `_images` folder at build time and all URLs are rewritten to point to this new location.

However, because any folders and files under `_static` are also copied regardless, the final website ends up with two copies of each image: one in the `_images` folder after the website builds, and another under `_static` because anything in `_static` will be copied anyways.

Seems like `_static` is meant to be used mostly for scripts, CSS and other static assets other than images and media content, so perhaps simply moving the `images` folder to the top-level `src` folder would be enough.

### PR DESCRIPTION
**Pull request by lochhh**
This PR closes #81.

This PR
- renames the `src/_static/images` directory and its contents to `src/images` 
- updates all occurrences of `_static/images` in the doc pages to `images`
- renames the ` src/_static/resources` directory and its contents to ` src/downloads`
- updates all occurrences of `_static/resources` in the doc pages to `downloads`

### CODE REVIEW

**Review by glopesdev — COMMENTED** [review]
@lochhh looking at examples online and in Sphinx's own [docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#images) it seems that the recommendation is to use local image paths without the leading `_`, i.e. using `src/images` instead of `src/_images`.

I'm guessing that `_` might be more recommended for sphinx infrastructure reserved paths.

**Comment by lochhh** [comment]
> @lochhh looking at examples online and in Sphinx's own [docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#images) it seems that the recommendation is to use local image paths without the leading `_`, i.e. using `src/images` instead of `src/_images`.
> 
> I'm guessing that `_` might be more recommended for sphinx infrastructure reserved paths.

Thanks @glopesdev. The issue (#81) is that Sphinx copies all images (regardless of where they are) into the `_images` dir, so we end up with duplicate copies of the images (one in the original dir and another in `_images`). If we drop the leading `_`, we will end up with duplicate copies of the images again.

**Comment by glopesdev** [comment]
> The issue (https://github.com/SainsburyWellcomeCentre/aeon_docs/issues/81) is that Sphinx copies all images (regardless of where they are) into the _images dir, so we end up with duplicate copies of the images (one in the original dir and another in _images).

Are you sure the images are being copied from the original dir? Don't forget to clean/delete the `html` folder to make sure no leftover files are there. Files outside of `_static` are not usually copied unless they are part of a processing pipeline.

For images that pipeline involves the assets being referenced in the articles and will be copied to `_images`. As long as the folder is outside of `_static` they should not be duplicated. I did a quick test which seems to verify this, but I am curious if you are observing something else.

**Comment by lochhh** [comment]
> > The issue (#81) is that Sphinx copies all images (regardless of where they are) into the _images dir, so we end up with duplicate copies of the images (one in the original dir and another in _images).
> 
> @lochhh Are you sure the images are being copied from the original dir? Don't forget to clean/delete the `html` folder to make sure no leftover files are there. Files outside of `_static` are not usually copied unless they are part of a processing pipeline.
> 
> For images, that pipeline involves the assets being referenced in the articles, and each image will be copied to `_images` with their URL rewritten in the final output. As long as the image source folder is outside of `_static` they should not be duplicated. I did a quick test which seems to verify this, but I am curious if you are observing something else.

Thanks @glopesdev you're right. I've now removed the `_` and made the same change for the downloadable files (BOM, wiring diagrams, building instructions).

**Review by glopesdev — APPROVED** [review]

**Pull request merged**
